"""
Shared HTML/CSS layout primitives for Halvix visualization pages.

These helpers were previously defined in ``visualization.charts`` and consumed
across the package by ``charts.py``, ``html_generator.py`` and
``pattern_charts.py`` via underscore-prefixed cross-module imports. Hosting
them in a dedicated layout module makes the package-internal contract
explicit — chart-rendering logic and HTML page scaffolding are now distinct
responsibilities, and ``charts.py`` no longer doubles as the visualization
layout vocabulary.

The leading underscore in each helper name is preserved to keep these as
package-private symbols: external callers should compose pages via the
higher-level renderers in ``charts``, ``pattern_charts`` and
``html_generator`` rather than reach for these primitives directly.
"""

from datetime import UTC, datetime


def _get_base_css() -> str:
    """
    Return the base CSS variables and reset styles shared across all pages.

    Returns:
        CSS string with root variables and base styles
    """
    return """
        :root {
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --text-primary: #e6edf3;
            --text-secondary: #8b949e;
            --accent-orange: #f7931a;
            --accent-blue: #58a6ff;
            --accent-green: #3fb950;
            --border-color: #30363d;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            line-height: 1.6;
        }
    """


def _get_header_css() -> str:
    """
    Return CSS for the compact page header.

    Returns:
        CSS string for header styling
    """
    return """
        header {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            padding: 0.5rem 2rem;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 0.75rem;
            position: relative;
        }

        .back-link {
            color: var(--text-secondary);
            text-decoration: none;
            font-size: 1.1rem;
            position: absolute;
            left: 1.25rem;
        }

        .back-link:hover {
            color: var(--accent-blue);
        }

        .header-content {
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .logo {
            font-size: 1.25rem;
        }

        header h1 {
            font-size: 1.1rem;
            font-weight: 700;
            background: linear-gradient(90deg, var(--accent-orange), var(--accent-blue));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
    """


def _get_footer_css() -> str:
    """
    Return CSS for the page footer.

    Returns:
        CSS string for footer styling
    """
    return """
        footer {
            text-align: center;
            padding: 0.75rem;
            border-top: 1px solid var(--border-color);
            color: var(--text-secondary);
            font-size: 0.75rem;
        }

        footer a {
            color: var(--accent-blue);
            text-decoration: none;
        }

        footer a:hover {
            text-decoration: underline;
        }

        footer .last-updated {
            opacity: 0.8;
        }
    """


def _get_header_html(back_link: str = "../index.html") -> str:
    """
    Return the HTML for the compact page header.

    Args:
        back_link: URL for the back arrow link

    Returns:
        HTML string for the header
    """
    return f"""
    <header>
        <a href="{back_link}" class="back-link">← Back</a>
        <div class="header-content">
            <div class="logo">📊</div>
            <h1>Halvix</h1>
        </div>
    </header>
    """


def _get_footer_html(last_updated: str | None = None) -> str:
    """
    Return the HTML for the page footer.

    Args:
        last_updated: Optional timestamp string for "Last updated" display.
                      If None, uses current datetime.

    Returns:
        HTML string for the footer
    """
    if last_updated is None:
        last_updated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    return f"""
    <footer>
        <p>
            Generated by <strong>Halvix</strong> •
            <a href="https://github.com/yohplala/halvix">Source Code</a> •
            Data from <a href="https://www.cryptocompare.com/">CryptoCompare</a>
            <span class="last-updated">• Last updated: {last_updated}</span>
        </p>
    </footer>
    """
