"""
Visualization module for Halvix.

Creates interactive Plotly charts for:
- TOTAL2 index across halving cycles
- BTC vs USD across halving cycles
- Interactive coin composition viewer
"""

from datetime import date, timedelta
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from config import (
    DAYS_AFTER_HALVING,
    DAYS_BEFORE_HALVING,
    HALVING_DATES,
    OUTPUT_DIR,
    TOTAL2_COMPOSITION_FILE,
    TOTAL2_INDEX_FILE,
)
from data.cache import PriceDataCache

# Color palettes
TOTAL2_COLORS = [
    "rgba(100, 149, 237, 0.5)",  # Cycle 1 - lightest blue
    "rgba(65, 105, 225, 0.7)",  # Cycle 2
    "rgba(30, 64, 175, 0.85)",  # Cycle 3
    "rgba(15, 32, 100, 1.0)",  # Cycle 4 - darkest blue
]

BTC_COLORS = [
    "rgba(255, 180, 100, 0.5)",  # Cycle 1 - lightest orange
    "rgba(255, 140, 0, 0.7)",  # Cycle 2
    "rgba(255, 100, 0, 0.85)",  # Cycle 3
    "rgba(230, 80, 0, 1.0)",  # Cycle 4 - darkest orange
]


def _get_page_template(title: str, chart_html: str) -> str:
    """
    Wrap a Plotly chart in a page template with consistent header/nav.

    Args:
        title: Page title for the browser tab
        chart_html: The Plotly chart HTML content

    Returns:
        Complete HTML page with header, nav, chart, and footer
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Halvix</title>
    <style>
        :root {{
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --text-primary: #e6edf3;
            --text-secondary: #8b949e;
            --accent-orange: #f7931a;
            --accent-blue: #58a6ff;
            --border-color: #30363d;
        }}

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            line-height: 1.6;
        }}

        header {{
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            padding: 2rem;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
        }}

        .logo {{
            font-size: 2rem;
            margin-bottom: 0.25rem;
        }}

        h1 {{
            font-size: 1.75rem;
            font-weight: 700;
            background: linear-gradient(90deg, var(--accent-orange), var(--accent-blue));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}

        .subtitle {{
            color: var(--text-secondary);
            font-size: 0.95rem;
            margin-top: 0.25rem;
        }}

        nav {{
            background: var(--bg-secondary);
            padding: 0.75rem 2rem;
            border-bottom: 1px solid var(--border-color);
        }}

        nav ul {{
            list-style: none;
            display: flex;
            gap: 2rem;
            justify-content: center;
        }}

        nav a {{
            color: var(--text-secondary);
            text-decoration: none;
            font-weight: 500;
            transition: color 0.2s;
        }}

        nav a:hover {{
            color: var(--accent-blue);
        }}

        .chart-container {{
            width: 100%;
            padding: 1rem;
        }}

        footer {{
            text-align: center;
            padding: 1.5rem;
            border-top: 1px solid var(--border-color);
            color: var(--text-secondary);
            font-size: 0.85rem;
        }}

        footer a {{
            color: var(--accent-blue);
            text-decoration: none;
        }}

        footer a:hover {{
            text-decoration: underline;
        }}

        @media (max-width: 768px) {{
            h1 {{
                font-size: 1.5rem;
            }}

            nav ul {{
                flex-wrap: wrap;
                gap: 1rem;
            }}
        }}
    </style>
</head>
<body>
    <header>
        <div class="logo">📊</div>
        <h1>Halvix Charts</h1>
        <p class="subtitle">{title}</p>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">Data Status</a></li>
            <li><a href="../charts.html">Charts</a></li>
            <li><a href="https://github.com/yohplala/halvix">GitHub</a></li>
        </ul>
    </nav>

    <div class="chart-container">
        {chart_html}
    </div>

    <footer>
        <p>
            Generated by <strong>Halvix</strong> •
            <a href="https://github.com/yohplala/halvix">Source Code</a> •
            Data from <a href="https://www.cryptocompare.com/">CryptoCompare</a>
        </p>
    </footer>
</body>
</html>
"""


def _write_chart_with_template(
    fig: go.Figure,
    output_path: Path,
    title: str,
) -> None:
    """
    Write a Plotly figure to HTML with a page template wrapper.

    Args:
        fig: Plotly figure to save
        output_path: Path to save HTML file
        title: Page title for the browser tab
    """
    # Generate the Plotly chart HTML (just the div and script, not full page)
    chart_html = fig.to_html(
        full_html=False,
        include_plotlyjs="cdn",
        config={"responsive": True},
    )
    # Wrap in page template
    full_html = _get_page_template(title, chart_html)
    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_html)


def get_cycle_data(
    df: pd.DataFrame,
    halving_date: date,
    price_col: str = "close",
    days_before: int = DAYS_BEFORE_HALVING,
    days_after: int = DAYS_AFTER_HALVING,
    normalize: bool = False,
) -> pd.DataFrame:
    """
    Extract data for a halving cycle and normalize to days from halving.

    Args:
        df: DataFrame with DatetimeIndex
        halving_date: The halving date for this cycle
        price_col: Column name for price data
        days_before: Days before halving to include
        days_after: Days after halving to include
        normalize: If True, normalize prices to 1.0 at halving day

    Returns:
        DataFrame with 'days_from_halving' column and optionally normalized price
    """
    start = halving_date - timedelta(days=days_before)
    end = halving_date + timedelta(days=days_after)

    # Filter to cycle range
    mask = (df.index.date >= start) & (df.index.date <= end)
    cycle_df = df[mask].copy()

    if cycle_df.empty:
        return cycle_df

    # Add days from halving
    cycle_df["days_from_halving"] = (
        (cycle_df.index.date - halving_date).astype("timedelta64[D]").astype(int)
    )

    if normalize and price_col in cycle_df.columns:
        # Find the value at day 0 (halving day) or closest day after
        halving_mask = cycle_df["days_from_halving"] >= 0
        if halving_mask.any():
            first_day = cycle_df[halving_mask].iloc[0]
            halving_value = first_day[price_col]
            if halving_value > 0:
                cycle_df["normalized"] = cycle_df[price_col] / halving_value

    return cycle_df


def create_btc_usd_normalized_chart(
    output_path: Path | None = None,
) -> go.Figure:
    """
    Create BTC vs USD chart with 4 halving cycles, normalized to 1.0 at halving.

    Args:
        output_path: Path to save HTML file

    Returns:
        Plotly Figure
    """
    # Load BTC-USD data
    cache = PriceDataCache()
    btc_df = cache.get_prices("btc", "USD")

    if btc_df is None or btc_df.empty:
        raise FileNotFoundError("BTC-USD price data not found. Run fetch-prices first.")

    # Create figure
    fig = go.Figure()

    # Add trace for each halving cycle
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1
        cycle_df = get_cycle_data(btc_df, halving_date, price_col="close", normalize=True)

        if cycle_df.empty or "normalized" not in cycle_df.columns:
            continue

        # Get actual halving price for hover
        halving_mask = cycle_df["days_from_halving"] >= 0
        if halving_mask.any():
            halving_price = cycle_df[halving_mask].iloc[0]["close"]
        else:
            halving_price = 0

        fig.add_trace(
            go.Scatter(
                x=cycle_df["days_from_halving"],
                y=cycle_df["normalized"],
                mode="lines",
                name=f"Cycle {cycle_num} ({halving_date.year})",
                line={"color": BTC_COLORS[i], "width": 2.5},
                hovertemplate=(
                    f"Cycle {cycle_num}<br>"
                    "Day: %{x}<br>"
                    "Multiplier: %{y:.2f}x<br>"
                    f"(Halving price: ${halving_price:,.0f})"
                    "<extra></extra>"
                ),
            )
        )

    # Layout
    fig.update_layout(
        title={
            "text": "Bitcoin (BTC) Price - Normalized to Halving Day",
            "font": {"size": 22, "family": "Arial Black"},
        },
        xaxis={
            "title": "Days from Halving",
            "tickmode": "linear",
            "dtick": 100,
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        yaxis={
            "title": "Price Multiplier (1.0 = Halving Day)",
            "type": "log",
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        legend={
            "yanchor": "top",
            "y": 0.99,
            "xanchor": "left",
            "x": 0.01,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=700,
        margin={"t": 80},
    )

    # Add vertical line at halving (day 0) - using add_shape for proper dotted line
    fig.add_shape(
        type="line",
        x0=0,
        x1=0,
        y0=0,
        y1=1,
        xref="x",
        yref="paper",
        line={"dash": "dot", "color": "rgba(200,200,200,0.5)", "width": 2},
    )
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 14},
    )

    # Add horizontal line at 1.0
    fig.add_hline(y=1, line={"dash": "dot", "color": "rgba(255,255,255,0.3)"})

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "Bitcoin (BTC) Price - Normalized to Halving Day",
        )

    return fig


def create_total2_dual_chart(
    output_path: Path | None = None,
) -> go.Figure:
    """
    Create TOTAL2 chart with 2 subplots: USD (left) and BTC (right).
    Both normalized to 1.0 at halving day.

    Note: Cycle 1 (2012) is excluded because the data is too sparse/small
    for meaningful visualization.

    Args:
        output_path: Path to save HTML file

    Returns:
        Plotly Figure
    """
    # Load TOTAL2 data (BTC denominated)
    if not TOTAL2_INDEX_FILE.exists():
        raise FileNotFoundError("TOTAL2 index not found. Run calculate-total2 first.")

    total2_btc_df = pd.read_parquet(TOTAL2_INDEX_FILE)

    # Load BTC-USD for conversion
    cache = PriceDataCache()
    btc_usd_df = cache.get_prices("btc", "USD")

    if btc_usd_df is None or btc_usd_df.empty:
        raise FileNotFoundError("BTC-USD price data not found. Run fetch-prices first.")

    # Calculate TOTAL2 in USD
    total2_usd_df = total2_btc_df.copy()
    # Align dates and multiply
    btc_usd_aligned = btc_usd_df["close"].reindex(total2_usd_df.index)
    total2_usd_df["total2_usd"] = total2_usd_df["total2_price"] * btc_usd_aligned

    # Create subplots
    fig = make_subplots(
        rows=1,
        cols=2,
        subplot_titles=("TOTAL2 vs USD (Normalized)", "TOTAL2 vs BTC (Normalized)"),
        horizontal_spacing=0.08,
    )

    # Add traces for each halving cycle (skip cycle 1 - insufficient data)
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1

        # Skip cycle 1 (2012) - data too sparse for meaningful visualization
        if cycle_num == 1:
            continue

        # USD chart (left)
        cycle_usd = get_cycle_data(
            total2_usd_df, halving_date, price_col="total2_usd", normalize=True
        )
        if not cycle_usd.empty and "normalized" in cycle_usd.columns:
            fig.add_trace(
                go.Scatter(
                    x=cycle_usd["days_from_halving"],
                    y=cycle_usd["normalized"],
                    mode="lines",
                    name=f"Cycle {cycle_num} ({halving_date.year})",
                    line={"color": TOTAL2_COLORS[i], "width": 2},
                    legendgroup=f"cycle{cycle_num}",
                    hovertemplate=(
                        f"Cycle {cycle_num}<br>"
                        "Day: %{x}<br>"
                        "Multiplier: %{y:.2f}x"
                        "<extra></extra>"
                    ),
                ),
                row=1,
                col=1,
            )

        # BTC chart (right)
        cycle_btc = get_cycle_data(
            total2_btc_df, halving_date, price_col="total2_price", normalize=True
        )
        if not cycle_btc.empty and "normalized" in cycle_btc.columns:
            fig.add_trace(
                go.Scatter(
                    x=cycle_btc["days_from_halving"],
                    y=cycle_btc["normalized"],
                    mode="lines",
                    name=f"Cycle {cycle_num} ({halving_date.year})",
                    line={"color": TOTAL2_COLORS[i], "width": 2},
                    legendgroup=f"cycle{cycle_num}",
                    showlegend=False,  # Only show in legend once
                    hovertemplate=(
                        f"Cycle {cycle_num}<br>"
                        "Day: %{x}<br>"
                        "Multiplier: %{y:.2f}x"
                        "<extra></extra>"
                    ),
                ),
                row=1,
                col=2,
            )

    # Update layout
    fig.update_layout(
        title={
            "text": "TOTAL2 Index - Normalized to Halving Day",
            "font": {"size": 22, "family": "Arial Black"},
            "x": 0.5,
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=600,
        legend={
            "yanchor": "top",
            "y": 0.99,
            "xanchor": "left",
            "x": 0.01,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        margin={"t": 100},
    )

    # Update axes
    for col in [1, 2]:
        fig.update_xaxes(
            title_text="Days from Halving",
            tickmode="linear",
            dtick=200,
            gridcolor="rgba(128, 128, 128, 0.2)",
            row=1,
            col=col,
        )
        fig.update_yaxes(
            title_text="Multiplier (1.0 = Halving)",
            type="log",
            gridcolor="rgba(128, 128, 128, 0.2)",
            row=1,
            col=col,
        )

    # Add vertical lines at halving for both charts - using add_shape for proper dotted line
    fig.add_shape(
        type="line",
        x0=0,
        x1=0,
        y0=0,
        y1=1,
        xref="x1",
        yref="paper",
        line={"dash": "dot", "color": "rgba(200,200,200,0.5)", "width": 2},
    )
    fig.add_shape(
        type="line",
        x0=0,
        x1=0,
        y0=0,
        y1=1,
        xref="x2",
        yref="paper",
        line={"dash": "dot", "color": "rgba(200,200,200,0.5)", "width": 2},
    )
    # Add halving annotation for both charts
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        xref="x1",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 12},
    )
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        xref="x2",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 12},
    )

    # Add horizontal lines at 1.0
    fig.add_hline(y=1, line={"dash": "dot", "color": "rgba(255,255,255,0.3)"}, row=1, col=1)
    fig.add_hline(y=1, line={"dash": "dot", "color": "rgba(255,255,255,0.3)"}, row=1, col=2)

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "TOTAL2 Index - Normalized to Halving Day (USD & BTC)",
        )

    return fig


def create_total2_halving_chart(
    output_path: Path | None = None,
    show_composition: bool = True,
) -> go.Figure:
    """
    Create TOTAL2 chart with halving cycles (absolute values).

    Note: Cycle 1 (2012) is excluded because the data is too sparse/small
    for meaningful visualization.

    Args:
        output_path: Path to save HTML file
        show_composition: If True, add interactive composition viewer

    Returns:
        Plotly Figure
    """
    # Load TOTAL2 data
    if not TOTAL2_INDEX_FILE.exists():
        raise FileNotFoundError("TOTAL2 index not found. Run calculate-total2 first.")

    total2_df = pd.read_parquet(TOTAL2_INDEX_FILE)

    # Load composition data if needed
    composition_df = None
    if show_composition and TOTAL2_COMPOSITION_FILE.exists():
        composition_df = pd.read_parquet(TOTAL2_COMPOSITION_FILE)

    # Create figure
    fig = go.Figure()

    # Add trace for each halving cycle (skip cycle 1 - insufficient data)
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1

        # Skip cycle 1 (2012) - data too sparse for meaningful visualization
        if cycle_num == 1:
            continue

        cycle_df = get_cycle_data(total2_df, halving_date, price_col="total2_price")

        if cycle_df.empty:
            continue

        # Prepare hover text with composition info
        if composition_df is not None:
            hover_texts = []
            for idx, row in cycle_df.iterrows():
                dt = idx.date()
                comp = composition_df[composition_df["date"] == dt]
                if not comp.empty:
                    top_coins = comp.nsmallest(10, "rank")["coin_id"].str.upper().tolist()
                    coins_str = ", ".join(top_coins)
                    hover_texts.append(
                        f"Date: {dt}<br>"
                        f"TOTAL2: {row['total2_price']:.8f} BTC<br>"
                        f"Coins: {row['coin_count']}<br>"
                        f"Top 10: {coins_str}"
                    )
                else:
                    hover_texts.append(
                        f"Date: {dt}<br>"
                        f"TOTAL2: {row['total2_price']:.8f} BTC<br>"
                        f"Coins: {row['coin_count']}"
                    )
        else:
            hover_texts = None

        fig.add_trace(
            go.Scatter(
                x=cycle_df["days_from_halving"],
                y=cycle_df["total2_price"],
                mode="lines",
                name=f"Cycle {cycle_num} ({halving_date.year})",
                line={"color": TOTAL2_COLORS[i], "width": 2},
                hovertemplate="%{text}<extra></extra>" if hover_texts else None,
                text=hover_texts,
            )
        )

    # Layout
    fig.update_layout(
        title={
            "text": "TOTAL2 Index Across Bitcoin Halving Cycles",
            "font": {"size": 20},
        },
        xaxis={
            "title": "Days from Halving",
            "tickmode": "linear",
            "dtick": 100,
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        yaxis={
            "title": "TOTAL2 (BTC)",
            "type": "log",
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        legend={
            "yanchor": "bottom",
            "y": 0.01,
            "xanchor": "right",
            "x": 0.99,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=600,
    )

    # Add vertical line at halving (day 0) - using add_shape for proper dotted line
    fig.add_shape(
        type="line",
        x0=0,
        x1=0,
        y0=0,
        y1=1,
        xref="x",
        yref="paper",
        line={"dash": "dot", "color": "rgba(200,200,200,0.5)", "width": 2},
    )
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 14},
    )

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "TOTAL2 Index Across Bitcoin Halving Cycles",
        )

    return fig


def create_btc_usd_halving_chart(
    output_path: Path | None = None,
) -> go.Figure:
    """
    Create BTC vs USD chart with 4 halving cycles (absolute values).

    Args:
        output_path: Path to save HTML file

    Returns:
        Plotly Figure
    """
    # Load BTC-USD data
    cache = PriceDataCache()
    btc_df = cache.get_prices("btc", "USD")

    if btc_df is None or btc_df.empty:
        raise FileNotFoundError("BTC-USD price data not found. Run fetch-prices first.")

    # Create figure
    fig = go.Figure()

    # Add trace for each halving cycle
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1
        cycle_df = get_cycle_data(btc_df, halving_date, price_col="close")

        if cycle_df.empty:
            continue

        fig.add_trace(
            go.Scatter(
                x=cycle_df["days_from_halving"],
                y=cycle_df["close"],
                mode="lines",
                name=f"Cycle {cycle_num} ({halving_date.year})",
                line={"color": BTC_COLORS[i], "width": 2},
                hovertemplate=("Day: %{x}<br>" "Price: $%{y:,.2f}<br>" "<extra></extra>"),
            )
        )

    # Layout
    fig.update_layout(
        title={
            "text": "Bitcoin (BTC) Price Across Halving Cycles",
            "font": {"size": 20},
        },
        xaxis={
            "title": "Days from Halving",
            "tickmode": "linear",
            "dtick": 100,
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        yaxis={
            "title": "BTC Price (USD)",
            "type": "log",
            "tickprefix": "$",
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        legend={
            "yanchor": "bottom",
            "y": 0.01,
            "xanchor": "right",
            "x": 0.99,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=600,
    )

    # Add vertical line at halving (day 0) - using add_shape for proper dotted line
    fig.add_shape(
        type="line",
        x0=0,
        x1=0,
        y0=0,
        y1=1,
        xref="x",
        yref="paper",
        line={"dash": "dot", "color": "rgba(200,200,200,0.5)", "width": 2},
    )
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 14},
    )

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "Bitcoin (BTC) Price Across Halving Cycles",
        )

    return fig


def create_composition_viewer_html(
    output_path: Path,
) -> dict[str, Path]:
    """
    Create HTML pages with interactive TOTAL2 composition viewer, split by month.

    Creates one page per month with navigation between months.

    Args:
        output_path: Base path for HTML files (will append month suffix)

    Returns:
        Dictionary mapping month key (e.g., "2024_01") to file path
    """
    import json

    # Load composition data
    if not TOTAL2_COMPOSITION_FILE.exists():
        raise FileNotFoundError("TOTAL2 composition not found. Run calculate-total2 first.")

    composition_df = pd.read_parquet(TOTAL2_COMPOSITION_FILE)

    # Get unique dates and group by month
    dates = sorted(composition_df["date"].unique())

    def get_month_key(d: date) -> str:
        """Get month key like '2024_01' from a date."""
        return f"{d.year}_{d.month:02d}"

    def get_month_display(month_key: str) -> str:
        """Get display name like 'Jan 2024' from month key."""
        year, month = month_key.split("_")
        month_names = [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
        ]
        return f"{month_names[int(month) - 1]} {year}"

    def get_cycle_info(d) -> str:
        """
        Get cycle day info for a date, showing which cycle(s) it belongs to.

        Returns string like "C4: Day 12" or "C3: Day 880 | C4: Day -5" for overlaps.
        """
        # Convert Pandas Timestamp to date if needed
        if hasattr(d, "date"):
            d = d.date()
        cycle_infos = []
        for i, halving_date in enumerate(HALVING_DATES):
            cycle_num = i + 1
            # Skip cycle 1 (not shown in charts)
            if cycle_num == 1:
                continue
            start = halving_date - timedelta(days=DAYS_BEFORE_HALVING)
            end = halving_date + timedelta(days=DAYS_AFTER_HALVING)
            if start <= d <= end:
                day_num = (d - halving_date).days
                cycle_infos.append(f"C{cycle_num}: Day {day_num}")
        return " | ".join(cycle_infos) if cycle_infos else ""

    # Get all unique months
    months = sorted({get_month_key(d) for d in dates})

    # Load TOTAL2 index for displaying values
    total2_df = pd.read_parquet(TOTAL2_INDEX_FILE)

    # Build month navigation table (shared across all pages)
    years_in_nav = sorted({m.split("_")[0] for m in months})
    month_letters = ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"]

    # Build a set of available months for quick lookup
    available_months = set(months)

    created_files = {}

    for month_key in months:
        # Parse year and month from key
        year, month = month_key.split("_")
        year = int(year)
        month = int(month)

        # Filter dates for this month
        month_dates = [d for d in dates if get_month_key(d) == month_key]

        # Find the last day of the previous month for cross-month comparison
        prev_month_last_day = None
        month_idx = months.index(month_key)
        if month_idx > 0:
            prev_month_key = months[month_idx - 1]
            prev_month_dates = [d for d in dates if get_month_key(d) == prev_month_key]
            if prev_month_dates:
                prev_month_last_day = max(prev_month_dates)

        # Create date options for this month with cycle day info
        date_options_list = []
        for d in month_dates:
            # Convert to date string for clean display
            date_str = d.date() if hasattr(d, "date") else d
            cycle_info = get_cycle_info(d)
            if cycle_info:
                display = f"{date_str}  ({cycle_info})"
            else:
                display = str(date_str)
            date_options_list.append(f'<option value="{d}">{display}</option>')
        date_options = "\n".join(date_options_list)

        # Create composition data as JSON for this month, including TOTAL2 value
        # Also include previous month's last day for cross-month comparison
        composition_by_date = {}

        # Add previous month's last day if available (for comparison only)
        if prev_month_last_day is not None:
            dt = prev_month_last_day
            day_comp = composition_df[composition_df["date"] == dt].sort_values("rank")
            total2_value = None
            if dt in total2_df.index:
                total2_value = float(total2_df.loc[dt, "total2_price"])
            elif hasattr(dt, "date") and pd.Timestamp(dt.date()) in total2_df.index:
                total2_value = float(total2_df.loc[pd.Timestamp(dt.date()), "total2_price"])

            composition_by_date[str(dt)] = {
                "total2_value": total2_value,
                "coins": [
                    {
                        "rank": int(row["rank"]),
                        "coin_id": row["coin_id"].upper(),
                        "volume": float(row["volume"]),
                        "weight": float(row["weight"]) * 100,
                        "price_btc": float(row["price_btc"]),
                    }
                    for _, row in day_comp.iterrows()
                ],
            }

        # Add this month's dates
        for dt in month_dates:
            day_comp = composition_df[composition_df["date"] == dt].sort_values("rank")
            # Get TOTAL2 value for this date
            total2_value = None
            if dt in total2_df.index:
                total2_value = float(total2_df.loc[dt, "total2_price"])
            elif hasattr(dt, "date") and pd.Timestamp(dt.date()) in total2_df.index:
                total2_value = float(total2_df.loc[pd.Timestamp(dt.date()), "total2_price"])

            composition_by_date[str(dt)] = {
                "total2_value": total2_value,
                "coins": [
                    {
                        "rank": int(row["rank"]),
                        "coin_id": row["coin_id"].upper(),
                        "volume": float(row["volume"]),
                        "weight": float(row["weight"]) * 100,
                        "price_btc": float(row["price_btc"]),
                    }
                    for _, row in day_comp.iterrows()
                ],
            }

        composition_json = json.dumps(composition_by_date)

        # Generate month navigation as a table (12 columns for months, rows for years)
        month_nav_rows = []
        for nav_year in years_in_nav:
            row_cells = [f'<td class="year-label">{nav_year}</td>']
            for m_idx in range(1, 13):
                m_key = f"{nav_year}_{m_idx:02d}"
                letter = month_letters[m_idx - 1]
                if m_key in available_months:
                    if m_key == month_key:
                        row_cells.append(
                            f'<td><span class="month-current" '
                            f'title="{get_month_display(m_key)}">{letter}</span></td>'
                        )
                    else:
                        row_cells.append(
                            f'<td><a href="total2_composition_{m_key}.html" '
                            f'class="month-link" title="{get_month_display(m_key)}">'
                            f"{letter}</a></td>"
                        )
                else:
                    # Month not available - show greyed out
                    row_cells.append(f'<td><span class="month-empty">{letter}</span></td>')
            month_nav_rows.append("<tr>" + "".join(row_cells) + "</tr>")
        month_nav_html = "\n".join(month_nav_rows)

        display_month = get_month_display(month_key)
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TOTAL2 Composition {display_month} - Halvix</title>
    <style>
        :root {{
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --text-primary: #e6edf3;
            --text-secondary: #8b949e;
            --accent-orange: #f7931a;
            --accent-blue: #58a6ff;
            --accent-green: #3fb950;
            --border-color: #30363d;
        }}

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            line-height: 1.6;
        }}

        header {{
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            padding: 2rem;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
        }}

        .logo {{
            font-size: 2rem;
            margin-bottom: 0.25rem;
        }}

        header h1 {{
            font-size: 1.75rem;
            font-weight: 700;
            background: linear-gradient(90deg, var(--accent-orange), var(--accent-blue));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}

        .subtitle {{
            color: var(--text-secondary);
            font-size: 0.95rem;
            margin-top: 0.25rem;
        }}

        nav {{
            background: var(--bg-secondary);
            padding: 0.75rem 2rem;
            border-bottom: 1px solid var(--border-color);
        }}

        nav ul {{
            list-style: none;
            display: flex;
            gap: 2rem;
            justify-content: center;
        }}

        nav a {{
            color: var(--text-secondary);
            text-decoration: none;
            font-weight: 500;
            transition: color 0.2s;
        }}

        nav a:hover {{
            color: var(--accent-blue);
        }}

        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }}

        .page-title {{
            color: var(--accent-blue);
            margin-bottom: 1rem;
        }}

        .month-nav {{
            margin-bottom: 1.5rem;
            display: flex;
            justify-content: center;
        }}

        .month-nav-table {{
            border-collapse: collapse;
            background: transparent;
        }}

        .month-nav-table td {{
            padding: 0.2rem 0.4rem;
            text-align: center;
            border: none;
            background: transparent;
        }}

        .month-nav-table .year-label {{
            font-weight: bold;
            color: var(--text-secondary);
            text-align: right;
            padding-right: 0.75rem;
            font-size: 0.85rem;
        }}

        .month-nav .month-link {{
            color: var(--accent-blue);
            text-decoration: none;
            font-family: monospace;
            font-size: 0.9rem;
        }}

        .month-nav .month-link:hover {{
            text-decoration: underline;
        }}

        .month-nav .month-current {{
            color: var(--accent-orange);
            font-weight: bold;
            font-family: monospace;
            font-size: 0.9rem;
        }}

        .month-nav .month-empty {{
            color: var(--border-color);
            font-family: monospace;
            font-size: 0.9rem;
        }}

        select {{
            padding: 0.5rem 1rem;
            font-size: 1rem;
            background: var(--bg-primary);
            color: var(--text-primary);
            border: 1px solid var(--border-color);
            border-radius: 4px;
            width: 100%;
            cursor: pointer;
        }}

        .stats-row {{
            display: flex;
            gap: 1.5rem;
            margin-bottom: 1.5rem;
            justify-content: center;
            flex-wrap: wrap;
        }}

        .stat {{
            background: var(--bg-secondary);
            padding: 1rem 1.5rem;
            border-radius: 8px;
            text-align: center;
            min-width: 160px;
        }}

        .stat-label {{
            font-size: 0.85rem;
            color: var(--text-secondary);
            margin-bottom: 0.25rem;
        }}

        .stat-value {{
            font-size: 1.25rem;
            font-weight: bold;
            color: var(--accent-green);
        }}

        .stat-value.blue {{
            color: var(--accent-blue);
        }}

        .stat-value.orange {{
            color: var(--accent-orange);
        }}

        .changes-row {{
            display: flex;
            gap: 1.5rem;
            margin-bottom: 1.5rem;
            justify-content: center;
            flex-wrap: wrap;
        }}

        .changes-box {{
            background: var(--bg-secondary);
            padding: 1rem 1.5rem;
            border-radius: 8px;
            text-align: center;
            min-width: 200px;
        }}

        .changes-box .label {{
            font-size: 0.85rem;
            color: var(--text-secondary);
            margin-bottom: 0.5rem;
        }}

        .changes-box .coins {{
            font-size: 0.95rem;
            font-weight: bold;
        }}

        .changes-box .coins.added {{
            color: var(--accent-green);
        }}

        .changes-box .coins.removed {{
            color: #f85149;
        }}

        .changes-box .coins.none {{
            color: var(--text-secondary);
            font-weight: normal;
            font-style: italic;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            background: var(--bg-secondary);
            border-radius: 8px;
            overflow: hidden;
        }}

        th, td {{
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid var(--border-color);
        }}

        th {{
            background: #21262d;
        }}

        .coin-symbol {{
            color: var(--accent-blue);
            font-weight: bold;
        }}

        .weight {{
            color: var(--accent-green);
        }}

        footer {{
            text-align: center;
            padding: 1.5rem;
            border-top: 1px solid var(--border-color);
            color: var(--text-secondary);
            font-size: 0.85rem;
            margin-top: 2rem;
        }}

        footer a {{
            color: var(--accent-blue);
            text-decoration: none;
        }}

        footer a:hover {{
            text-decoration: underline;
        }}

        @media (max-width: 768px) {{
            header h1 {{
                font-size: 1.5rem;
            }}

            nav ul {{
                flex-wrap: wrap;
                gap: 1rem;
            }}

            .stats-row {{
                flex-direction: column;
                gap: 1rem;
            }}

            .changes-row {{
                flex-direction: column;
                gap: 1rem;
            }}

            .stat, .changes-box {{
                min-width: auto;
                width: 100%;
            }}
        }}
    </style>
</head>
<body>
    <header>
        <div class="logo">📊</div>
        <h1>Halvix Charts</h1>
        <p class="subtitle">TOTAL2 Composition Viewer - {display_month}</p>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">Data Status</a></li>
            <li><a href="../charts.html">Charts</a></li>
            <li><a href="https://github.com/yohplala/halvix">GitHub</a></li>
        </ul>
    </nav>

    <div class="container">
        <h2 class="page-title">🧩 TOTAL2 Composition Viewer</h2>

        <div class="month-nav">
            <table class="month-nav-table">
                {month_nav_html}
            </table>
        </div>

        <div class="stats-row">
            <div class="stat">
                <div class="stat-label">Select Date</div>
                <select id="date-select">
                    {date_options}
                </select>
            </div>
            <div class="stat">
                <div class="stat-label">TOTAL2 Value</div>
                <div class="stat-value" id="total2-value">-</div>
            </div>
            <div class="stat">
                <div class="stat-label">Coins in TOTAL2</div>
                <div class="stat-value blue" id="coin-count">-</div>
            </div>
            <div class="stat">
                <div class="stat-label">Total Volume</div>
                <div class="stat-value" id="total-volume">-</div>
            </div>
        </div>

        <div class="changes-row">
            <div class="changes-box">
                <div class="label">↑ New vs Previous Day</div>
                <div class="coins added" id="coins-added">-</div>
            </div>
            <div class="changes-box">
                <div class="label">↓ Removed vs Previous Day</div>
                <div class="coins removed" id="coins-removed">-</div>
            </div>
        </div>

        <table id="composition-table">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Coin</th>
                    <th>Weight</th>
                    <th>Price (BTC)</th>
                    <th>Volume (BTC)</th>
                </tr>
            </thead>
            <tbody id="composition-body">
            </tbody>
        </table>
    </div>

    <footer>
        <p>
            Generated by <strong>Halvix</strong> •
            <a href="https://github.com/yohplala/halvix">Source Code</a> •
            Data from <a href="https://www.cryptocompare.com/">CryptoCompare</a>
        </p>
    </footer>

    <script>
        const compositionData = {composition_json};
        const sortedDates = Object.keys(compositionData).sort();

        function getPreviousDate(dateStr) {{
            const idx = sortedDates.indexOf(dateStr);
            if (idx > 0) {{
                return sortedDates[idx - 1];
            }}
            return null;
        }}

        function updateTable(dateStr) {{
            const dayData = compositionData[dateStr];
            const tbody = document.getElementById('composition-body');

            if (!dayData || !dayData.coins || dayData.coins.length === 0) {{
                tbody.innerHTML = '<tr><td colspan="5">No data for this date</td></tr>';
                document.getElementById('total2-value').textContent = '-';
                document.getElementById('coin-count').textContent = '-';
                document.getElementById('total-volume').textContent = '-';
                document.getElementById('coins-added').textContent = '-';
                document.getElementById('coins-added').className = 'coins none';
                document.getElementById('coins-removed').textContent = '-';
                document.getElementById('coins-removed').className = 'coins none';
                return;
            }}

            const coins = dayData.coins;
            const total2Value = dayData.total2_value;

            // Display TOTAL2 value
            if (total2Value !== null && total2Value !== undefined) {{
                document.getElementById('total2-value').textContent = total2Value.toFixed(8) + ' BTC';
            }} else {{
                document.getElementById('total2-value').textContent = '-';
            }}

            document.getElementById('coin-count').textContent = coins.length;
            const totalVol = coins.reduce((sum, c) => sum + c.volume, 0);
            document.getElementById('total-volume').textContent = totalVol.toFixed(2) + ' BTC';

            // Calculate changes vs previous day
            const prevDateStr = getPreviousDate(dateStr);
            const prevData = prevDateStr ? compositionData[prevDateStr] : null;

            if (prevData && prevData.coins) {{
                const currentCoins = new Set(coins.map(c => c.coin_id));
                const prevCoins = new Set(prevData.coins.map(c => c.coin_id));

                const added = [...currentCoins].filter(c => !prevCoins.has(c));
                const removed = [...prevCoins].filter(c => !currentCoins.has(c));

                const addedEl = document.getElementById('coins-added');
                const removedEl = document.getElementById('coins-removed');

                if (added.length > 0) {{
                    addedEl.textContent = added.join(', ');
                    addedEl.className = 'coins added';
                }} else {{
                    addedEl.textContent = 'None';
                    addedEl.className = 'coins none';
                }}

                if (removed.length > 0) {{
                    removedEl.textContent = removed.join(', ');
                    removedEl.className = 'coins removed';
                }} else {{
                    removedEl.textContent = 'None';
                    removedEl.className = 'coins none';
                }}
            }} else {{
                document.getElementById('coins-added').textContent = 'N/A (first day)';
                document.getElementById('coins-added').className = 'coins none';
                document.getElementById('coins-removed').textContent = 'N/A (first day)';
                document.getElementById('coins-removed').className = 'coins none';
            }}

            tbody.innerHTML = coins.map(coin => `
                <tr>
                    <td>${{coin.rank}}</td>
                    <td class="coin-symbol">${{coin.coin_id}}</td>
                    <td class="weight">${{coin.weight.toFixed(2)}}%</td>
                    <td>${{coin.price_btc.toFixed(8)}}</td>
                    <td>${{coin.volume.toFixed(2)}}</td>
                </tr>
            `).join('');
        }}

        document.getElementById('date-select').addEventListener('change', (e) => {{
            updateTable(e.target.value);
        }});

        // Initialize with last date
        const select = document.getElementById('date-select');
        select.selectedIndex = select.options.length - 1;
        updateTable(select.value);
    </script>
</body>
</html>
"""

        # Construct filename for this month
        month_output_path = output_path.parent / f"total2_composition_{month_key}.html"
        month_output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(month_output_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        created_files[month_key] = month_output_path

    # Create a redirect from the original path to the latest month
    latest_month = max(months)
    redirect_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="refresh" content="0; url=total2_composition_{latest_month}.html">
    <title>Redirecting...</title>
</head>
<body>
    <p>Redirecting to <a href="total2_composition_{latest_month}.html">TOTAL2 Composition {get_month_display(latest_month)}</a>...</p>
</body>
</html>
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(redirect_html)

    return created_files


def generate_all_charts(output_dir: Path | None = None) -> dict[str, Path]:
    """
    Generate all visualization charts.

    Args:
        output_dir: Directory to save charts (default: OUTPUT_DIR/charts)

    Returns:
        Dictionary mapping chart name to file path
    """
    if output_dir is None:
        output_dir = OUTPUT_DIR / "charts"
    output_dir.mkdir(parents=True, exist_ok=True)

    paths = {}

    # BTC vs USD normalized chart (main chart)
    btc_norm_path = output_dir / "btc_usd_normalized.html"
    create_btc_usd_normalized_chart(btc_norm_path)
    paths["btc_normalized"] = btc_norm_path

    # TOTAL2 dual chart (USD and BTC side by side)
    total2_dual_path = output_dir / "total2_dual_normalized.html"
    create_total2_dual_chart(total2_dual_path)
    paths["total2_dual"] = total2_dual_path

    # Legacy charts (absolute values)
    total2_path = output_dir / "total2_halving_cycles.html"
    create_total2_halving_chart(total2_path)
    paths["total2"] = total2_path

    btc_path = output_dir / "btc_halving_cycles.html"
    create_btc_usd_halving_chart(btc_path)
    paths["btc"] = btc_path

    # Composition viewer (split by quarter)
    comp_path = output_dir / "total2_composition.html"
    quarter_paths = create_composition_viewer_html(comp_path)
    paths["composition"] = comp_path
    for quarter_key, quarter_path in quarter_paths.items():
        paths[f"composition_{quarter_key}"] = quarter_path

    return paths
