"""
Visualization module for Halvix.

Creates interactive Plotly charts for:
- TOTAL2 index across halving cycles
- BTC vs USD across halving cycles
- Interactive coin composition viewer
"""

from datetime import date, timedelta
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from config import (
    DAYS_AFTER_HALVING,
    DAYS_BEFORE_HALVING,
    HALVING_DATES,
    OUTPUT_DIR,
    TOTAL2_COMPOSITION_FILE,
    TOTAL2_INDEX_FILE,
)
from data.cache import PriceDataCache

# Color palettes
TOTAL2_COLORS = [
    "rgba(100, 149, 237, 0.5)",  # Cycle 1 - lightest blue
    "rgba(65, 105, 225, 0.7)",  # Cycle 2
    "rgba(30, 64, 175, 0.85)",  # Cycle 3
    "rgba(15, 32, 100, 1.0)",  # Cycle 4 - darkest blue
]

BTC_COLORS = [
    "rgba(255, 180, 100, 0.5)",  # Cycle 1 - lightest orange
    "rgba(255, 140, 0, 0.7)",  # Cycle 2
    "rgba(255, 100, 0, 0.85)",  # Cycle 3
    "rgba(230, 80, 0, 1.0)",  # Cycle 4 - darkest orange
]


def _get_page_template(title: str, chart_html: str) -> str:
    """
    Wrap a Plotly chart in a page template with consistent header/nav.

    Args:
        title: Page title for the browser tab
        chart_html: The Plotly chart HTML content

    Returns:
        Complete HTML page with header, nav, chart, and footer
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Halvix</title>
    <style>
        :root {{
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --text-primary: #e6edf3;
            --text-secondary: #8b949e;
            --accent-orange: #f7931a;
            --accent-blue: #58a6ff;
            --border-color: #30363d;
        }}

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            line-height: 1.6;
        }}

        header {{
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            padding: 2rem;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
        }}

        .logo {{
            font-size: 2rem;
            margin-bottom: 0.25rem;
        }}

        h1 {{
            font-size: 1.75rem;
            font-weight: 700;
            background: linear-gradient(90deg, var(--accent-orange), var(--accent-blue));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}

        .subtitle {{
            color: var(--text-secondary);
            font-size: 0.95rem;
            margin-top: 0.25rem;
        }}

        nav {{
            background: var(--bg-secondary);
            padding: 0.75rem 2rem;
            border-bottom: 1px solid var(--border-color);
        }}

        nav ul {{
            list-style: none;
            display: flex;
            gap: 2rem;
            justify-content: center;
        }}

        nav a {{
            color: var(--text-secondary);
            text-decoration: none;
            font-weight: 500;
            transition: color 0.2s;
        }}

        nav a:hover {{
            color: var(--accent-blue);
        }}

        .chart-container {{
            width: 100%;
            padding: 1rem;
        }}

        footer {{
            text-align: center;
            padding: 1.5rem;
            border-top: 1px solid var(--border-color);
            color: var(--text-secondary);
            font-size: 0.85rem;
        }}

        footer a {{
            color: var(--accent-blue);
            text-decoration: none;
        }}

        footer a:hover {{
            text-decoration: underline;
        }}

        @media (max-width: 768px) {{
            h1 {{
                font-size: 1.5rem;
            }}

            nav ul {{
                flex-wrap: wrap;
                gap: 1rem;
            }}
        }}
    </style>
</head>
<body>
    <header>
        <div class="logo">📊</div>
        <h1>Halvix Charts</h1>
        <p class="subtitle">{title}</p>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">Data Status</a></li>
            <li><a href="../charts.html">Charts</a></li>
            <li><a href="https://github.com/yohplala/halvix">GitHub</a></li>
        </ul>
    </nav>

    <div class="chart-container">
        {chart_html}
    </div>

    <footer>
        <p>
            Generated by <strong>Halvix</strong> •
            <a href="https://github.com/yohplala/halvix">Source Code</a> •
            Data from <a href="https://www.cryptocompare.com/">CryptoCompare</a>
        </p>
    </footer>
</body>
</html>
"""


def _write_chart_with_template(
    fig: go.Figure,
    output_path: Path,
    title: str,
) -> None:
    """
    Write a Plotly figure to HTML with a page template wrapper.

    Args:
        fig: Plotly figure to save
        output_path: Path to save HTML file
        title: Page title for the browser tab
    """
    # Generate the Plotly chart HTML (just the div and script, not full page)
    chart_html = fig.to_html(
        full_html=False,
        include_plotlyjs="cdn",
        config={"responsive": True},
    )
    # Wrap in page template
    full_html = _get_page_template(title, chart_html)
    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_html)


def get_cycle_data(
    df: pd.DataFrame,
    halving_date: date,
    price_col: str = "close",
    days_before: int = DAYS_BEFORE_HALVING,
    days_after: int = DAYS_AFTER_HALVING,
    normalize: bool = False,
) -> pd.DataFrame:
    """
    Extract data for a halving cycle and normalize to days from halving.

    Args:
        df: DataFrame with DatetimeIndex
        halving_date: The halving date for this cycle
        price_col: Column name for price data
        days_before: Days before halving to include
        days_after: Days after halving to include
        normalize: If True, normalize prices to 1.0 at halving day

    Returns:
        DataFrame with 'days_from_halving' column and optionally normalized price
    """
    start = halving_date - timedelta(days=days_before)
    end = halving_date + timedelta(days=days_after)

    # Filter to cycle range
    mask = (df.index.date >= start) & (df.index.date <= end)
    cycle_df = df[mask].copy()

    if cycle_df.empty:
        return cycle_df

    # Add days from halving
    cycle_df["days_from_halving"] = (
        (cycle_df.index.date - halving_date).astype("timedelta64[D]").astype(int)
    )

    if normalize and price_col in cycle_df.columns:
        # Find the value at day 0 (halving day) or closest day after
        halving_mask = cycle_df["days_from_halving"] >= 0
        if halving_mask.any():
            first_day = cycle_df[halving_mask].iloc[0]
            halving_value = first_day[price_col]
            if halving_value > 0:
                cycle_df["normalized"] = cycle_df[price_col] / halving_value

    return cycle_df


def create_btc_usd_normalized_chart(
    output_path: Path | None = None,
) -> go.Figure:
    """
    Create BTC vs USD chart with 4 halving cycles, normalized to 1.0 at halving.

    Args:
        output_path: Path to save HTML file

    Returns:
        Plotly Figure
    """
    # Load BTC-USD data
    cache = PriceDataCache()
    btc_df = cache.get_prices("btc", "USD")

    if btc_df is None or btc_df.empty:
        raise FileNotFoundError("BTC-USD price data not found. Run fetch-prices first.")

    # Create figure
    fig = go.Figure()

    # Add trace for each halving cycle
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1
        cycle_df = get_cycle_data(btc_df, halving_date, price_col="close", normalize=True)

        if cycle_df.empty or "normalized" not in cycle_df.columns:
            continue

        # Get actual halving price for hover
        halving_mask = cycle_df["days_from_halving"] >= 0
        if halving_mask.any():
            halving_price = cycle_df[halving_mask].iloc[0]["close"]
        else:
            halving_price = 0

        fig.add_trace(
            go.Scatter(
                x=cycle_df["days_from_halving"],
                y=cycle_df["normalized"],
                mode="lines",
                name=f"Cycle {cycle_num} ({halving_date.year})",
                line={"color": BTC_COLORS[i], "width": 2.5},
                hovertemplate=(
                    f"Cycle {cycle_num}<br>"
                    "Day: %{x}<br>"
                    "Multiplier: %{y:.2f}x<br>"
                    f"(Halving price: ${halving_price:,.0f})"
                    "<extra></extra>"
                ),
            )
        )

    # Layout
    fig.update_layout(
        title={
            "text": "Bitcoin (BTC) Price - Normalized to Halving Day",
            "font": {"size": 22, "family": "Arial Black"},
        },
        xaxis={
            "title": "Days from Halving",
            "tickmode": "linear",
            "dtick": 100,
            "gridcolor": "rgba(128, 128, 128, 0.2)",
            "zeroline": True,
            "zerolinecolor": "white",
            "zerolinewidth": 2,
        },
        yaxis={
            "title": "Price Multiplier (1.0 = Halving Day)",
            "type": "log",
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        legend={
            "yanchor": "top",
            "y": 0.99,
            "xanchor": "left",
            "x": 0.01,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=700,
        margin={"t": 80},
    )

    # Add vertical line at halving (day 0)
    fig.add_vline(x=0, line_dash="dot", line_color="rgba(200,200,200,0.5)", line_width=2)
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 14},
    )

    # Add horizontal line at 1.0
    fig.add_hline(y=1, line_dash="dot", line_color="rgba(255,255,255,0.3)")

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "Bitcoin (BTC) Price - Normalized to Halving Day",
        )

    return fig


def create_total2_dual_chart(
    output_path: Path | None = None,
) -> go.Figure:
    """
    Create TOTAL2 chart with 2 subplots: USD (left) and BTC (right).
    Both normalized to 1.0 at halving day.

    Note: Cycle 1 (2012) is excluded because the data is too sparse/small
    for meaningful visualization.

    Args:
        output_path: Path to save HTML file

    Returns:
        Plotly Figure
    """
    # Load TOTAL2 data (BTC denominated)
    if not TOTAL2_INDEX_FILE.exists():
        raise FileNotFoundError("TOTAL2 index not found. Run calculate-total2 first.")

    total2_btc_df = pd.read_parquet(TOTAL2_INDEX_FILE)

    # Load BTC-USD for conversion
    cache = PriceDataCache()
    btc_usd_df = cache.get_prices("btc", "USD")

    if btc_usd_df is None or btc_usd_df.empty:
        raise FileNotFoundError("BTC-USD price data not found. Run fetch-prices first.")

    # Calculate TOTAL2 in USD
    total2_usd_df = total2_btc_df.copy()
    # Align dates and multiply
    btc_usd_aligned = btc_usd_df["close"].reindex(total2_usd_df.index)
    total2_usd_df["total2_usd"] = total2_usd_df["total2_price"] * btc_usd_aligned

    # Create subplots
    fig = make_subplots(
        rows=1,
        cols=2,
        subplot_titles=("TOTAL2 vs USD (Normalized)", "TOTAL2 vs BTC (Normalized)"),
        horizontal_spacing=0.08,
    )

    # Add traces for each halving cycle (skip cycle 1 - insufficient data)
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1

        # Skip cycle 1 (2012) - data too sparse for meaningful visualization
        if cycle_num == 1:
            continue

        # USD chart (left)
        cycle_usd = get_cycle_data(
            total2_usd_df, halving_date, price_col="total2_usd", normalize=True
        )
        if not cycle_usd.empty and "normalized" in cycle_usd.columns:
            fig.add_trace(
                go.Scatter(
                    x=cycle_usd["days_from_halving"],
                    y=cycle_usd["normalized"],
                    mode="lines",
                    name=f"Cycle {cycle_num} ({halving_date.year})",
                    line={"color": TOTAL2_COLORS[i], "width": 2},
                    legendgroup=f"cycle{cycle_num}",
                    hovertemplate=(
                        f"Cycle {cycle_num}<br>"
                        "Day: %{x}<br>"
                        "Multiplier: %{y:.2f}x"
                        "<extra></extra>"
                    ),
                ),
                row=1,
                col=1,
            )

        # BTC chart (right)
        cycle_btc = get_cycle_data(
            total2_btc_df, halving_date, price_col="total2_price", normalize=True
        )
        if not cycle_btc.empty and "normalized" in cycle_btc.columns:
            fig.add_trace(
                go.Scatter(
                    x=cycle_btc["days_from_halving"],
                    y=cycle_btc["normalized"],
                    mode="lines",
                    name=f"Cycle {cycle_num} ({halving_date.year})",
                    line={"color": TOTAL2_COLORS[i], "width": 2},
                    legendgroup=f"cycle{cycle_num}",
                    showlegend=False,  # Only show in legend once
                    hovertemplate=(
                        f"Cycle {cycle_num}<br>"
                        "Day: %{x}<br>"
                        "Multiplier: %{y:.2f}x"
                        "<extra></extra>"
                    ),
                ),
                row=1,
                col=2,
            )

    # Update layout
    fig.update_layout(
        title={
            "text": "TOTAL2 Index - Normalized to Halving Day",
            "font": {"size": 22, "family": "Arial Black"},
            "x": 0.5,
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=600,
        legend={
            "yanchor": "top",
            "y": 0.99,
            "xanchor": "left",
            "x": 0.01,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        margin={"t": 100},
    )

    # Update axes
    for col in [1, 2]:
        fig.update_xaxes(
            title_text="Days from Halving",
            tickmode="linear",
            dtick=200,
            gridcolor="rgba(128, 128, 128, 0.2)",
            zeroline=True,
            zerolinecolor="white",
            zerolinewidth=2,
            row=1,
            col=col,
        )
        fig.update_yaxes(
            title_text="Multiplier (1.0 = Halving)",
            type="log",
            gridcolor="rgba(128, 128, 128, 0.2)",
            row=1,
            col=col,
        )

    # Add vertical lines at halving
    for col in [1, 2]:
        fig.add_vline(
            x=0, line_dash="dot", line_color="rgba(200,200,200,0.5)", line_width=2, row=1, col=col
        )
    # Add halving annotation for left chart only
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        xref="x1",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 12},
    )

    # Add horizontal lines at 1.0
    fig.add_hline(y=1, line_dash="dot", line_color="rgba(255,255,255,0.3)", row=1, col=1)
    fig.add_hline(y=1, line_dash="dot", line_color="rgba(255,255,255,0.3)", row=1, col=2)

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "TOTAL2 Index - Normalized to Halving Day (USD & BTC)",
        )

    return fig


def create_total2_halving_chart(
    output_path: Path | None = None,
    show_composition: bool = True,
) -> go.Figure:
    """
    Create TOTAL2 chart with halving cycles (absolute values).

    Note: Cycle 1 (2012) is excluded because the data is too sparse/small
    for meaningful visualization.

    Args:
        output_path: Path to save HTML file
        show_composition: If True, add interactive composition viewer

    Returns:
        Plotly Figure
    """
    # Load TOTAL2 data
    if not TOTAL2_INDEX_FILE.exists():
        raise FileNotFoundError("TOTAL2 index not found. Run calculate-total2 first.")

    total2_df = pd.read_parquet(TOTAL2_INDEX_FILE)

    # Load composition data if needed
    composition_df = None
    if show_composition and TOTAL2_COMPOSITION_FILE.exists():
        composition_df = pd.read_parquet(TOTAL2_COMPOSITION_FILE)

    # Create figure
    fig = go.Figure()

    # Add trace for each halving cycle (skip cycle 1 - insufficient data)
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1

        # Skip cycle 1 (2012) - data too sparse for meaningful visualization
        if cycle_num == 1:
            continue

        cycle_df = get_cycle_data(total2_df, halving_date, price_col="total2_price")

        if cycle_df.empty:
            continue

        # Prepare hover text with composition info
        if composition_df is not None:
            hover_texts = []
            for idx, row in cycle_df.iterrows():
                dt = idx.date()
                comp = composition_df[composition_df["date"] == dt]
                if not comp.empty:
                    top_coins = comp.nsmallest(10, "rank")["coin_id"].str.upper().tolist()
                    coins_str = ", ".join(top_coins)
                    hover_texts.append(
                        f"Date: {dt}<br>"
                        f"TOTAL2: {row['total2_price']:.8f} BTC<br>"
                        f"Coins: {row['coin_count']}<br>"
                        f"Top 10: {coins_str}"
                    )
                else:
                    hover_texts.append(
                        f"Date: {dt}<br>"
                        f"TOTAL2: {row['total2_price']:.8f} BTC<br>"
                        f"Coins: {row['coin_count']}"
                    )
        else:
            hover_texts = None

        fig.add_trace(
            go.Scatter(
                x=cycle_df["days_from_halving"],
                y=cycle_df["total2_price"],
                mode="lines",
                name=f"Cycle {cycle_num} ({halving_date.year})",
                line={"color": TOTAL2_COLORS[i], "width": 2},
                hovertemplate="%{text}<extra></extra>" if hover_texts else None,
                text=hover_texts,
            )
        )

    # Layout
    fig.update_layout(
        title={
            "text": "TOTAL2 Index Across Bitcoin Halving Cycles",
            "font": {"size": 20},
        },
        xaxis={
            "title": "Days from Halving",
            "tickmode": "linear",
            "dtick": 100,
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        yaxis={
            "title": "TOTAL2 (BTC)",
            "type": "log",
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        legend={
            "yanchor": "bottom",
            "y": 0.01,
            "xanchor": "right",
            "x": 0.99,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=600,
    )

    # Add vertical line at halving (day 0)
    fig.add_vline(x=0, line_dash="dot", line_color="rgba(200,200,200,0.5)", line_width=2)
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 14},
    )

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "TOTAL2 Index Across Bitcoin Halving Cycles",
        )

    return fig


def create_btc_usd_halving_chart(
    output_path: Path | None = None,
) -> go.Figure:
    """
    Create BTC vs USD chart with 4 halving cycles (absolute values).

    Args:
        output_path: Path to save HTML file

    Returns:
        Plotly Figure
    """
    # Load BTC-USD data
    cache = PriceDataCache()
    btc_df = cache.get_prices("btc", "USD")

    if btc_df is None or btc_df.empty:
        raise FileNotFoundError("BTC-USD price data not found. Run fetch-prices first.")

    # Create figure
    fig = go.Figure()

    # Add trace for each halving cycle
    for i, halving_date in enumerate(HALVING_DATES):
        cycle_num = i + 1
        cycle_df = get_cycle_data(btc_df, halving_date, price_col="close")

        if cycle_df.empty:
            continue

        fig.add_trace(
            go.Scatter(
                x=cycle_df["days_from_halving"],
                y=cycle_df["close"],
                mode="lines",
                name=f"Cycle {cycle_num} ({halving_date.year})",
                line={"color": BTC_COLORS[i], "width": 2},
                hovertemplate=("Day: %{x}<br>" "Price: $%{y:,.2f}<br>" "<extra></extra>"),
            )
        )

    # Layout
    fig.update_layout(
        title={
            "text": "Bitcoin (BTC) Price Across Halving Cycles",
            "font": {"size": 20},
        },
        xaxis={
            "title": "Days from Halving",
            "tickmode": "linear",
            "dtick": 100,
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        yaxis={
            "title": "BTC Price (USD)",
            "type": "log",
            "tickprefix": "$",
            "gridcolor": "rgba(128, 128, 128, 0.2)",
        },
        legend={
            "yanchor": "bottom",
            "y": 0.01,
            "xanchor": "right",
            "x": 0.99,
            "bgcolor": "rgba(0,0,0,0.5)",
        },
        template="plotly_dark",
        paper_bgcolor="#0d1117",
        plot_bgcolor="#0d1117",
        hovermode="x unified",
        height=600,
    )

    # Add vertical line at halving (day 0)
    fig.add_vline(x=0, line_dash="dot", line_color="rgba(200,200,200,0.5)", line_width=2)
    fig.add_annotation(
        x=0,
        y=1.02,
        yref="paper",
        text="⚡ HALVING",
        showarrow=False,
        font={"color": "rgba(180,180,180,0.8)", "size": 14},
    )

    if output_path:
        _write_chart_with_template(
            fig,
            output_path,
            "Bitcoin (BTC) Price Across Halving Cycles",
        )

    return fig


def create_composition_viewer_html(
    output_path: Path,
) -> dict[int, Path]:
    """
    Create HTML pages with interactive TOTAL2 composition viewer, split by year.

    Creates one page per year with navigation between years.

    Args:
        output_path: Base path for HTML files (will append year suffix)

    Returns:
        Dictionary mapping year to file path
    """
    import json

    # Load composition data
    if not TOTAL2_COMPOSITION_FILE.exists():
        raise FileNotFoundError("TOTAL2 composition not found. Run calculate-total2 first.")

    composition_df = pd.read_parquet(TOTAL2_COMPOSITION_FILE)

    # Get unique dates and group by year
    dates = sorted(composition_df["date"].unique())
    years = sorted({d.year for d in dates})

    created_files = {}

    for year in years:
        # Filter dates for this year
        year_dates = [d for d in dates if d.year == year]

        # Create date options for this year
        date_options = "\n".join([f'<option value="{d}">{d}</option>' for d in year_dates])

        # Create composition data as JSON for this year only
        composition_by_date = {}
        for dt in year_dates:
            day_comp = composition_df[composition_df["date"] == dt].sort_values("rank")
            composition_by_date[str(dt)] = [
                {
                    "rank": int(row["rank"]),
                    "coin_id": row["coin_id"].upper(),
                    "volume": float(row["volume"]),
                    "weight": float(row["weight"]) * 100,
                    "price_btc": float(row["price_btc"]),
                }
                for _, row in day_comp.iterrows()
            ]

        composition_json = json.dumps(composition_by_date)

        # Generate year navigation links
        year_nav_items = []
        for y in years:
            if y == year:
                year_nav_items.append(f'<span class="year-current">{y}</span>')
            else:
                year_nav_items.append(
                    f'<a href="total2_composition_{y}.html" class="year-link">{y}</a>'
                )
        year_nav_html = " | ".join(year_nav_items)

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TOTAL2 Composition {year} - Halvix</title>
    <style>
        :root {{
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --text-primary: #e6edf3;
            --text-secondary: #8b949e;
            --accent-orange: #f7931a;
            --accent-blue: #58a6ff;
            --accent-green: #3fb950;
            --border-color: #30363d;
        }}

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            line-height: 1.6;
        }}

        header {{
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            padding: 2rem;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
        }}

        .logo {{
            font-size: 2rem;
            margin-bottom: 0.25rem;
        }}

        header h1 {{
            font-size: 1.75rem;
            font-weight: 700;
            background: linear-gradient(90deg, var(--accent-orange), var(--accent-blue));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}

        .subtitle {{
            color: var(--text-secondary);
            font-size: 0.95rem;
            margin-top: 0.25rem;
        }}

        nav {{
            background: var(--bg-secondary);
            padding: 0.75rem 2rem;
            border-bottom: 1px solid var(--border-color);
        }}

        nav ul {{
            list-style: none;
            display: flex;
            gap: 2rem;
            justify-content: center;
        }}

        nav a {{
            color: var(--text-secondary);
            text-decoration: none;
            font-weight: 500;
            transition: color 0.2s;
        }}

        nav a:hover {{
            color: var(--accent-blue);
        }}

        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }}

        .page-title {{
            color: var(--accent-blue);
            margin-bottom: 1rem;
        }}

        .year-nav {{
            margin-bottom: 1.5rem;
            padding: 0.75rem 1rem;
            background: var(--bg-secondary);
            border-radius: 8px;
            text-align: center;
        }}

        .year-nav .year-link {{
            color: var(--accent-blue);
            text-decoration: none;
            padding: 0.25rem 0.5rem;
        }}

        .year-nav .year-link:hover {{
            text-decoration: underline;
        }}

        .year-nav .year-current {{
            color: var(--accent-orange);
            font-weight: bold;
            padding: 0.25rem 0.5rem;
        }}

        .controls {{
            margin-bottom: 2rem;
        }}

        select {{
            padding: 0.5rem 1rem;
            font-size: 1rem;
            background: var(--bg-secondary);
            color: var(--text-primary);
            border: 1px solid var(--border-color);
            border-radius: 4px;
        }}

        .stats {{
            display: flex;
            gap: 2rem;
            margin-bottom: 1.5rem;
        }}

        .stat {{
            background: var(--bg-secondary);
            padding: 1rem;
            border-radius: 8px;
        }}

        .stat-value {{
            font-size: 1.5rem;
            font-weight: bold;
            color: var(--accent-green);
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            background: var(--bg-secondary);
            border-radius: 8px;
            overflow: hidden;
        }}

        th, td {{
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid var(--border-color);
        }}

        th {{
            background: #21262d;
        }}

        .coin-symbol {{
            color: var(--accent-blue);
            font-weight: bold;
        }}

        .weight {{
            color: var(--accent-green);
        }}

        footer {{
            text-align: center;
            padding: 1.5rem;
            border-top: 1px solid var(--border-color);
            color: var(--text-secondary);
            font-size: 0.85rem;
            margin-top: 2rem;
        }}

        footer a {{
            color: var(--accent-blue);
            text-decoration: none;
        }}

        footer a:hover {{
            text-decoration: underline;
        }}

        @media (max-width: 768px) {{
            header h1 {{
                font-size: 1.5rem;
            }}

            nav ul {{
                flex-wrap: wrap;
                gap: 1rem;
            }}

            .stats {{
                flex-direction: column;
                gap: 1rem;
            }}
        }}
    </style>
</head>
<body>
    <header>
        <div class="logo">📊</div>
        <h1>Halvix Charts</h1>
        <p class="subtitle">TOTAL2 Composition Viewer - {year}</p>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">Data Status</a></li>
            <li><a href="../charts.html">Charts</a></li>
            <li><a href="https://github.com/yohplala/halvix">GitHub</a></li>
        </ul>
    </nav>

    <div class="container">
        <h2 class="page-title">🧩 TOTAL2 Composition Viewer</h2>

        <div class="year-nav">
            <strong>Year:</strong> {year_nav_html}
        </div>

        <div class="controls">
            <label for="date-select">Select Date:</label>
            <select id="date-select">
                {date_options}
            </select>
        </div>

        <div class="stats">
            <div class="stat">
                <div>Coins in TOTAL2</div>
                <div class="stat-value" id="coin-count">-</div>
            </div>
            <div class="stat">
                <div>Total Volume</div>
                <div class="stat-value" id="total-volume">-</div>
            </div>
        </div>

        <table id="composition-table">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Coin</th>
                    <th>Weight</th>
                    <th>Price (BTC)</th>
                    <th>Volume (BTC)</th>
                </tr>
            </thead>
            <tbody id="composition-body">
            </tbody>
        </table>
    </div>

    <footer>
        <p>
            Generated by <strong>Halvix</strong> •
            <a href="https://github.com/yohplala/halvix">Source Code</a> •
            Data from <a href="https://www.cryptocompare.com/">CryptoCompare</a>
        </p>
    </footer>

    <script>
        const compositionData = {composition_json};

        function updateTable(dateStr) {{
            const data = compositionData[dateStr] || [];
            const tbody = document.getElementById('composition-body');

            if (data.length === 0) {{
                tbody.innerHTML = '<tr><td colspan="5">No data for this date</td></tr>';
                document.getElementById('coin-count').textContent = '-';
                document.getElementById('total-volume').textContent = '-';
                return;
            }}

            document.getElementById('coin-count').textContent = data.length;
            const totalVol = data.reduce((sum, c) => sum + c.volume, 0);
            document.getElementById('total-volume').textContent = totalVol.toFixed(2) + ' BTC';

            tbody.innerHTML = data.map(coin => `
                <tr>
                    <td>${{coin.rank}}</td>
                    <td class="coin-symbol">${{coin.coin_id}}</td>
                    <td class="weight">${{coin.weight.toFixed(2)}}%</td>
                    <td>${{coin.price_btc.toFixed(8)}}</td>
                    <td>${{coin.volume.toFixed(2)}}</td>
                </tr>
            `).join('');
        }}

        document.getElementById('date-select').addEventListener('change', (e) => {{
            updateTable(e.target.value);
        }});

        // Initialize with last date
        const select = document.getElementById('date-select');
        select.selectedIndex = select.options.length - 1;
        updateTable(select.value);
    </script>
</body>
</html>
"""

        # Construct filename for this year
        year_output_path = output_path.parent / f"total2_composition_{year}.html"
        year_output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(year_output_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        created_files[year] = year_output_path

    # Create a redirect from the original path to the latest year
    latest_year = max(years)
    redirect_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="refresh" content="0; url=total2_composition_{latest_year}.html">
    <title>Redirecting...</title>
</head>
<body>
    <p>Redirecting to <a href="total2_composition_{latest_year}.html">TOTAL2 Composition {latest_year}</a>...</p>
</body>
</html>
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(redirect_html)

    return created_files


def generate_all_charts(output_dir: Path | None = None) -> dict[str, Path]:
    """
    Generate all visualization charts.

    Args:
        output_dir: Directory to save charts (default: OUTPUT_DIR/charts)

    Returns:
        Dictionary mapping chart name to file path
    """
    if output_dir is None:
        output_dir = OUTPUT_DIR / "charts"
    output_dir.mkdir(parents=True, exist_ok=True)

    paths = {}

    # BTC vs USD normalized chart (main chart)
    btc_norm_path = output_dir / "btc_usd_normalized.html"
    create_btc_usd_normalized_chart(btc_norm_path)
    paths["btc_normalized"] = btc_norm_path

    # TOTAL2 dual chart (USD and BTC side by side)
    total2_dual_path = output_dir / "total2_dual_normalized.html"
    create_total2_dual_chart(total2_dual_path)
    paths["total2_dual"] = total2_dual_path

    # Legacy charts (absolute values)
    total2_path = output_dir / "total2_halving_cycles.html"
    create_total2_halving_chart(total2_path)
    paths["total2"] = total2_path

    btc_path = output_dir / "btc_halving_cycles.html"
    create_btc_usd_halving_chart(btc_path)
    paths["btc"] = btc_path

    # Composition viewer (split by year)
    comp_path = output_dir / "total2_composition.html"
    year_paths = create_composition_viewer_html(comp_path)
    paths["composition"] = comp_path
    for year, year_path in year_paths.items():
        paths[f"composition_{year}"] = year_path

    return paths
